name: antlr4_c3
description: A grammar agnostic code completion engine for ANTLR4 based parsers
version: 1.0.0+1
repository: https://github.com/CorvusYe/antlr4-c3/tree/main/ports/dart

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  antlr4: ^4.13.2
  logging: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
